/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * createuser.java
 *
 * Created on Aug 23, 2012, 7:17:26 AM
 */

package main;

import java.awt.HeadlessException;
import java.sql.SQLException;

/**
 *
 * @author Nirmal-PC
 */
public class createuser extends javax.swing.JPanel {

    /** Creates new form createuser */
    public createuser() {
        initComponents();
    }

    public void usercreation(db obj) {
        if (emptychecker()) {
            String prvlges = "0 0 0";
            if (prv.getText().trim().equals("0")) {
                prvlges = "1 1 1";
            }
            try {
                obj.connection.createStatement().execute("insert into `caes`.`account_info` (`username`,`password`,`Name`,`privillages`,`dets`) values('" + username.getText().trim() + "','" + pas.getText().trim() + "','" + name.getText().trim() + "','" + prv.getText().trim() + "','" + prvlges + "')");
                reseter();
            } catch (java.sql.SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Username alrdy exist", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
        else
            javax.swing.JOptionPane.showMessageDialog(null, "Required Field is empty!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        pas = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        prv = new javax.swing.JTextField();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(134, 226, 110, 23);
        add(username);
        username.setBounds(134, 38, 110, 20);
        add(pas);
        pas.setBounds(134, 64, 110, 20);
        add(name);
        name.setBounds(134, 95, 110, 20);
        add(prv);
        prv.setBounds(134, 126, 110, 20);

        jLabel109.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel109.setText("User Name");
        add(jLabel109);
        jLabel109.setBounds(30, 100, 91, 17);

        jLabel110.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel110.setText("Password");
        add(jLabel110);
        jLabel110.setBounds(30, 70, 91, 17);

        jLabel111.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel111.setText("Full Name");
        add(jLabel111);
        jLabel111.setBounds(30, 40, 91, 17);

        jLabel112.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel112.setText("Privelege");
        add(jLabel112);
        jLabel112.setBounds(30, 130, 91, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/backgndbig.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 690, 330);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        db obj = new db();

        obj.connectToDB("caes");
        usercreation(obj);


        obj.DisconnectFromDB();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pas;
    private javax.swing.JTextField prv;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    private boolean emptychecker() {
       if(username.getText().isEmpty() || pas.getText().isEmpty() || name.getText().isEmpty() || prv.getText().isEmpty())
        return false;
       else
        return true;

    }
    private void reseter(){

        username.setText(null);  pas.setText(null);  name.setText(null);  prv.setText(null);
    }

}
