
package main;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class home extends javax.swing.JPanel {

    /** Creates new form home */
    public home(String user) {
        
        initComponents();
        setSize(845,440);
        jLabel2.setText(user);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fb = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        fb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fbMouseClicked(evt);
            }
        });
        add(fb);
        fb.setBounds(730, 340, 110, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("User Friendliness");
        add(jLabel4);
        jLabel4.setBounds(70, 190, 160, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Saves time");
        add(jLabel5);
        jLabel5.setBounds(70, 210, 240, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Reduction of workload");
        add(jLabel6);
        jLabel6.setBounds(70, 230, 190, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Impressive GUI");
        add(jLabel8);
        jLabel8.setBounds(70, 270, 210, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Robust and Reliable");
        add(jLabel7);
        jLabel7.setBounds(70, 250, 200, 20);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Customization as per user needs");
        add(jLabel9);
        jLabel9.setBounds(70, 290, 260, 20);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Constantly updated applicants stats");
        add(jLabel10);
        jLabel10.setBounds(70, 310, 270, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/home2.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 460);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setForeground(new java.awt.Color(0, 19, 52));
        jLabel2.setText("112");
        add(jLabel2);
        jLabel2.setBounds(90, 10, 120, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void fbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbMouseClicked
        // TODO add your handling code here:
        URI uri=null;
        try {
            uri = new URI("https://www.facebook.com/CAESfast");
        } catch (URISyntaxException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (Desktop.isDesktopSupported()) {
      try {
        Desktop.getDesktop().browse(uri);
      } catch (IOException e) { /* TODO: error handling */ }
    } else { /* TODO: error handling */ }

    }//GEN-LAST:event_fbMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
