/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * prvsetter.java
 *
 * Created on Aug 23, 2012, 2:44:47 AM
 */

package main;


import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Nirmal-PC
 */
public class prvsetter extends javax.swing.JPanel {

    /** Creates new form prvsetter */
    public prvsetter() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ses = new javax.swing.JCheckBox();
        shed = new javax.swing.JCheckBox();
        stat = new javax.swing.JCheckBox();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(690, 330));
        setMinimumSize(new java.awt.Dimension(690, 330));
        setLayout(null);

        ses.setText("Sessions");
        ses.setOpaque(false);
        ses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesActionPerformed(evt);
            }
        });
        add(ses);
        ses.setBounds(32, 83, 100, 23);

        shed.setText("Scheduler");
        shed.setOpaque(false);
        add(shed);
        shed.setBounds(32, 124, 110, 23);

        stat.setText("Statistics");
        stat.setOpaque(false);
        add(stat);
        stat.setBounds(32, 165, 120, 23);
        add(username);
        username.setBounds(105, 41, 178, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Username");
        add(jLabel1);
        jLabel1.setBounds(32, 35, 69, 30);

        jButton1.setText("apply changes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(105, 247, 190, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/backgndbig.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 690, 330);
    }// </editor-fold>//GEN-END:initComponents

    private void sesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        db obj = new db();

        obj.connectToDB("caes");
        if(isUserValid(username.getText().trim(),obj))
            {
            StringBuffer tobeSet=null;
            int[] arr = {0,0,0};
            if(ses.isSelected())
                arr[0]=1;
            if(shed.isSelected())
                arr[1]=1;
            if(stat.isSelected())
                arr[2]=1;
        obj.insert("update `caes`.`account_info` set `dets` = '"+arr[0]+" "+arr[1]+" "+arr[2]+"' where username = \""+username.getText().trim()+"\"");
        }else{JOptionPane.showMessageDialog(null, "Incorrect Username","Error",JOptionPane.ERROR_MESSAGE);}


        obj.DisconnectFromDB();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox ses;
    private javax.swing.JCheckBox shed;
    private javax.swing.JCheckBox stat;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    private boolean isUserValid(String name,db obj) {
    try{
     java.sql.ResultSet rs = obj.connection.createStatement().executeQuery("select username from `caes`.`account_info` where username=\""+name+"\"");
     rs.next();
     return true;
    }catch(java.sql.SQLException e){System.out.println(e.getMessage());return false;}
    }

}

